augment3d:
  scale: [0.95, 1.05]
  rotate: [-0.3925, 0.3925]
  translate: 0

model:
  encoders:
    lidar:
      voxelize_reduce: false
      voxelize:
        max_num_points: 10
        point_cloud_range: ${point_cloud_range}
        voxel_size:  [0.8, 0.8, 8]
        max_voxels: [120000, 160000]
      backbone:
        type: PointPillarsEncoder
        pts_voxel_encoder: 
          type: PillarFeatureNet
          in_channels: 4
          voxel_size:  [0.8, 0.8, 8]
          point_cloud_range: ${point_cloud_range}
        pts_middle_encoder: 
          type: PointPillarsScatter
          output_shape: [128, 128]
    camera:
      vtransform:
        type: LSSV2XTransform
        image_size: ${image_size}
        xbound: [-51.2, 51.2, 0.8]
        ybound: [-51.2, 51.2, 0.8]
        zbound: [-10.0, 10.0, 20.0]
        dbound: [1.0, 60.0, 1.0]
  heads:
    object:
      test_cfg:
        nms_type:
          - circle
          - rotate
          - rotate
          - circle
          - rotate
          - rotate
        nms_scale:
          - [1.0]
          - [1.0, 1.0]
          - [1.0, 1.0]
          - [1.0]
          - [1.0, 1.0]
          - [2.5, 4.0]

lr_config: null
